CREATE TABLE pasteboxes(
                           ID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
                           DATA TEXT NOT NULL ,
                           STATUS VARCHAR(15) NOT NULL ,
                           CREATED_AT timestamp NOT NULL,
                           EXPIRES_AT timestamp,
                           HASH varchar
);
